title: ARAI
description: Analyse- und Recherche-Software zur KI-gestützten Analyse antidemokratischer Bewegungen online – teledash
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
github:
  repository_url: https://github.com/ARAI-Telegram
